### ISSUE TITLE
Profanity in commit messages

### ISSUE THREAD

**Issue by edvinklaebo** [Granerud/dndChar.Api#4]
I wish there wasn't so much profanity in your commit messages. 😄

**Comment by NullableInt** [comment]
I'm sorry, but I can't do that edvinklaebo

**Comment by edvinklaebo** [comment]
![image](https://user-images.githubusercontent.com/4660058/66459522-79613e00-ea75-11e9-9ebc-be60e8a7e7be.png)

**Comment by NullableInt** [comment]
Stop that, this is a very serious repo only for serious buisness 🐒
